POST http://localhost:8080/users
Authorization: Basic jj@test.com abcd
Content-Type: application/json

{
  "firstName": "JJ2",
  "lastName": "Jack",
  "email": "jj2@test.com",
  "password": "abcd",
  "roles": ["admin", "user"]
}

###
GET http://localhost:8080/users
Authorization: Basic jj@test.com abcd