POST http://localhost:8080/employees
Content-Type: application/json

{
  "id": 2,
  "firstName": "Edward",
  "lastName": "Doe",
  "address": "1000 N 10th St"
}

###
GET http://localhost:8080/employees